"use strict";
window.addEventListener("load", async () => {
  const results=[];
  const assert=(condition,text)=>{if(!condition)throw new Error(text);results.push("PASS "+text);};
  const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async fn=>{for(let i=0;i<60;i++){if(fn())return;await pause(50);}throw new Error("Timed out waiting for panel");};
  try {
    const host=window.SlackSparkTest,main=document.querySelector("#main-editor"),thread=document.querySelector("#thread-editor");
    assert(host.collectMessages(main).length===1&&host.collectMessages(main)[0].author==="Main author","main context excludes thread and hidden messages");
    assert(host.collectMessages(thread).length===1&&host.collectMessages(thread)[0].author==="Thread author","thread context excludes main channel");
    host.open(main);await wait(()=>host.frame?.contentWindow.SparkPanelTest);
    const panel=host.frame.contentWindow,api=panel.SparkPanelTest,doc=panel.document;
    await api.ready;await wait(()=>api.getState().context.messages.length===1);
    let calls=0,lastPayload;
    panel.SparkDemoTransport=async(type,payload)=>{
      if(type!=="spark:suggest")return {provider:"direct",has_key:false,mode:"demo"};
      calls++;lastPayload=payload;
      return {mode:"demo",summary_tr:"<img src=x onerror=alert(1)>",note_tr:"Synthetic test",replies:[{style:"short",text:"Thanks for the update."},{style:"friendly",text:"Thanks, that helps!"},{style:"professional",text:"Thank you for clarifying."}]};
    };
    assert(calls===0,"opening context makes no suggestion request");
    await api.generateReplies();
    assert(calls===0,"unknown identity prevents generation");
    doc.querySelector("#reply-as").value="Main author";
    doc.querySelector("#reply-as").dispatchEvent(new panel.Event("input"));
    await api.generateReplies();
    assert(calls===1&&doc.querySelectorAll(".reply-card").length===3,"one action produces three suggestions");
    assert(!doc.querySelector(".insight img"),"untrusted output rendered as text");
    main.textContent="A newer draft";
    assert(!host.insertReply("overwrite",host.revision).ok&&main.textContent==="A newer draft","changed Slack draft is preserved");
    host.capture();await pause(50);
    assert(host.insertReply("A reviewed reply",host.revision).ok&&main.textContent==="A reviewed reply","explicit insertion fills the draft");
    let keyEvents=0;main.addEventListener("keydown",()=>keyEvents++);
    host.insertReply("Another reviewed reply",host.revision);
    assert(keyEvents===0,"insertion never simulates a send shortcut");
    doc.querySelector("#intent").value="Teşekkür et. ığüşöç";
    let leaked=0;const capture=e=>{leaked++;e.preventDefault();};document.addEventListener("keydown",capture,true);
    doc.querySelector("#intent").dispatchEvent(new panel.KeyboardEvent("keydown",{key:"x",bubbles:true,composed:true,cancelable:true}));
    document.removeEventListener("keydown",capture,true);
    assert(leaked===0,"input events cannot reach parent Slack handlers");
    api.switchTab("settings");
    assert(!doc.querySelector("#settings-view").hidden&&doc.querySelector("#reply-view").hidden,"settings opens inside the same panel");
    await api.savePreference("ui_language","en");
    assert(doc.querySelector("#settings-tab").textContent.includes("Settings")&&doc.querySelector("label[for=api-key]").textContent.includes("API key"),"settings and main view share interface language");
    await api.savePreference("ui_language","zh-CN");
    assert(doc.documentElement.lang==="zh-CN"&&doc.querySelector("#settings-tab").textContent.includes("设置")&&doc.querySelector("#reply-tab").textContent.includes("回复"),"Chinese applies to both settings and replies");
    assert(JSON.parse(localStorage.getItem("slackSparkPreferences")).ui_language==="zh-CN","Chinese preference persists");
    await api.savePreference("ui_language","en");
    await api.savePreference("reply_language","tr");await api.savePreference("theme","light");
    assert(doc.documentElement.dataset.theme==="light","light theme applies to the whole panel");
    doc.querySelector("#language-button").click();
    assert(!doc.querySelector("#language-menu").hidden&&!doc.querySelector("select"),"language choices use an icon popover rather than visible dropdowns");
    api.switchTab("reply");await api.generateReplies();
    assert(lastPayload.ui_language==="en"&&lastPayload.reply_language==="tr"&&lastPayload.intent.includes("ığüşöç"),"instruction and language choices reach request payload");
    doc.querySelector("h1").dispatchEvent(new panel.PointerEvent("pointerdown",{bubbles:true}));
    assert(host.opened,"clicking inside panel keeps it open");
    document.body.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true}));
    assert(!host.opened,"outside click closes panel");
    host.open(main);await pause(80);
    assert(doc.querySelector("#intent").value.includes("ığüşöç"),"reopening same conversation preserves instructions");
    host.place();const rect=host.frame.getBoundingClientRect();
    assert(rect.top>=0&&rect.bottom<=innerHeight+1&&rect.left>=0&&rect.right<=innerWidth+1,"panel stays inside viewport");
    const revision=host.revision;
    history.pushState({},"","/tests.html?different-channel");
    assert(!host.insertReply("wrong conversation",revision).ok,"navigation blocks stale insertion");
    host.close();await pause(30);
    assert(doc.querySelectorAll(".reply-card").length===0,"closing clears suggestions");
    await api.savePreference("theme","dark");
    assert(doc.documentElement.dataset.theme==="dark","dark theme works");
    const prefs=JSON.parse(localStorage.getItem("slackSparkPreferences"));
    assert(prefs.ui_language==="en"&&prefs.reply_language==="tr"&&prefs.theme==="dark","preferences persist without conversation text");
    document.querySelector("#test-results").textContent="ALL PASSED\n"+results.join("\n");document.title="PASS Spark Reply";
  } catch(error){document.querySelector("#test-results").textContent="FAILED "+error.message+"\n"+results.join("\n");document.title="FAIL Spark Reply";}
});
